// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createNewPost = `-- name: CreateNewPost :one
INSERT INTO posts (id, created_at, updated_at, published_at, title, url, description, feed_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, created_at, updated_at, published_at, title, url, description, feed_id
`

type CreateNewPostParams struct {
	ID          uuid.UUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	PublishedAt sql.NullTime
	Title       string
	Url         string
	Description sql.NullString
	FeedID      uuid.UUID
}

func (q *Queries) CreateNewPost(ctx context.Context, arg CreateNewPostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createNewPost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PublishedAt,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.FeedID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.FeedID,
	)
	return i, err
}

const createPosts = `-- name: CreatePosts :many
INSERT INTO posts (id, created_at, updated_at, published_at, title, url, description, feed_id)
SELECT
    unnest($1::uuid[]),
    unnest($2::timestamp[]),
    unnest($3::timestamp[]),
    unnest($4::timestamp[]),
    unnest($5::text[]),
    unnest($6::text[]),
    unnest($7::text[]),
    unnest($8::uuid[])
RETURNING id, created_at, updated_at, published_at, title, url, description, feed_id
`

type CreatePostsParams struct {
	Ids          []uuid.UUID
	CreatedAts   []time.Time
	UpdatedAts   []time.Time
	PublishedAts []time.Time
	Titles       []string
	Urls         []string
	Descriptions []string
	FeedIds      []uuid.UUID
}

func (q *Queries) CreatePosts(ctx context.Context, arg CreatePostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, createPosts,
		pq.Array(arg.Ids),
		pq.Array(arg.CreatedAts),
		pq.Array(arg.UpdatedAts),
		pq.Array(arg.PublishedAts),
		pq.Array(arg.Titles),
		pq.Array(arg.Urls),
		pq.Array(arg.Descriptions),
		pq.Array(arg.FeedIds),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsForAUser = `-- name: GetPostsForAUser :many
WITH feeds_user_follows AS (
    SELECT id, created_at, updated_at, user_id, feed_id FROM feed_follows
    WHERE user_id = $1
)
SELECT posts.id, posts.created_at, posts.updated_at, posts.published_at, posts.title, posts.url, posts.description, posts.feed_id FROM posts
INNER JOIN feeds_user_follows ON posts.feed_id = feeds_user_follows.feed_id
LIMIT $2
`

type GetPostsForAUserParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) GetPostsForAUser(ctx context.Context, arg GetPostsForAUserParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForAUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
